name: 'Terraform'

defaults:
  run:
    shell: bash
    working-driectory: CHAP12/cert/

on:
  push:
    branches:
    - main

jobs:
  terrafrom:
    runs-on: ubuntu-latest
    name: Terraform
    environment: dev
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6
        terraform_wrapper: false
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -no-color -out tf.plan
    - name: Terraform Apply
      run: terraform apply -input=false tf.plan
